# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1d1dd913361ae0c280526ada1ade9f87d3ae87f96f18982d323c8a6a63cac99a30461389a45f05a50cdc06c7d83610dbd6c2d7137ff002c3397f93d6cbcd4ce

test:
  secret_key_base: 6151f97d5a98c0c95269b89dff9ff26a39bf47d694b6451d1a66b152bc35666e379d21fe82a71eb48b498f6819b27570b43dff8c1715cc13dc25e02f7327d530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
